name: portfolio_3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gif: ^2.3.0
  animate_do: ^4.2.0
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1 
  peanut: ^6.0.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0

flutter_native_splash:
  web: true
  web_image_mode: center
  android: false
  ios: false
  fullscreen: true
  
  image: assets/images/splash_logo.png
  background_image: assets/images/splash_background.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PPNeueMontreal
      fonts:
        - asset: assets/fonts/PPNeueMontreal-Regular.otf
    - family: Acidic
      fonts:
        - asset: assets/fonts/Acidic-Regular.otf