import 'package:portfolio_3/models/project.dart';
import 'package:portfolio_3/utils/constants.dart';

class ProjectsManager {
  static final List<Project> projects = [
    Project(
      name: 'EventsJo',
      logo: kEventsJoLogo,
      banner: kEventsJoBanner,
      platform: 'Cross-Platform',
      type: 'Application',
      isHovered: false,
      screenshots: kEventsJoScreenshots,
      segments: kEventsJoSegments,
      github: kEventsJoGithub,
      video: kEventsJoVideo,
      website: kEventsJoWebsite,
    ),
    Project(
      name: 'Concentrated',
      logo: kConcentratedLogo,
      banner: kConcentratedBanner,
      platform: 'Cross-Platform',
      type: 'Application',
      screenshots: kConcentratedScreenshots,
      segments: kConcentratedSegments,
      github: kConcentratedGithub,
      isHovered: false,
    ),
    Project(
      name: 'Suqareo',
      logo: kSquareoLogo,
      banner: kSquareoBanner,
      platform: 'Cross-Platform',
      type: 'Application',
      screenshots: kSquareoScreenshots,
      segments: kSquareoSegments,
      github: kSquareoGithub,
      website: kSquareoWebsite,
      video: kSquareoVideo,
      isHovered: false,
    ),
    Project(
      name: 'Audio Resumer',
      logo: kAudioResumerLogo,
      banner: kAudioResumerBanner,
      platform: 'Web',
      type: 'Extension',
      screenshots: kAudioResumerScreenshots,
      segments: kAudioResumerSegments,
      github: kAudioResumerGithub,
      isHovered: false,
    ),
    Project(
      name: 'Draw Over It',
      logo: kDrawOverItLogo,
      banner: kDrawOverItBanner,
      platform: 'Desktop',
      type: 'Application',
      segments: kDrawOverItSegments,
      github: kDrawOverItGithub,
      video: kDrawOverItVideo,
      isHovered: false,
    ),
    Project(
      name: 'Windows Sidebar',
      logo: kWindowsSidebarLogo,
      banner: kWindowsSidebarBanner,
      platform: 'Windows',
      type: 'Application',
      segments: kWindowsSidebarSegments,
      github: kWindowsSidebarGithub,
      isHovered: false,
    ),
    Project(
      name: 'Rapid Rounds',
      logo: kRapidRoundsLogo,
      banner: kRapidRoundsBanner,
      platform: 'Mobile',
      type: 'Application',
      segments: kRapidRoundsSegments,
      github: kRapidRoundsGithub,
      screenshots: kRapidRoundsScreenshots,
      isHovered: false,
    ),
    Project(
      name: 'Portfolio',
      logo: kPortfolioLogo,
      banner: kPortfolioBanner,
      platform: 'Web',
      type: 'Website',
      segments: kPortfolioSegments,
      github: kPortfolioGithub,
      isHovered: false,
    ),
    Project(
      name: 'EventsJo Backend',
      logo: kEventsJoBackendLogo,
      banner: kEventsJoBackendBanner,
      platform: 'Cross-Platform',
      type: 'Backend',
      segments: kEventsJoBackendSegments,
      github: kEventsJoBackendGithub,
      isHovered: false,
    ),
  ];
}
